spring.application.name=md04-ss05

spring.datasource.url=jdbc:mysql://localhost:3306/md04_ss05
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true